export const data = {
    "4": {
      id: 4,
      name: "3-6번 4",
      number: 4,
      gId: 5,
      gNum: 5,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.174",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130108200",
      angle: 14,
      useYn: 1,
      delYn: 0
    },
    "5": {
      id: 5,
      name: "3-5번 3",
      number: 5,
      gId: 2,
      gNum: 2,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.175",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "51",
      angle: -15,
      useYn: 1,
      delYn: 0
    },
    "6": {
      id: 6,
      name: "3-4번 3",
      number: 6,
      gId: 5,
      gNum: 5,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.176",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130109700",
      angle: -29,
      useYn: 1,
      delYn: 0
    },
    "7": {
      id: 7,
      name: "3-3번 4",
      number: 7,
      gId: 5,
      gNum: 5,
      locType: 0,
      lcType: 5,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.177",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130110500",
      angle: -13,
      useYn: 1,
      delYn: 0
    },
    "8": {
      id: 8,
      name: "3-2번 3",
      number: 8,
      gId: 5,
      gNum: 5,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.178",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130110900",
      angle: -4,
      useYn: 1,
      delYn: 0
    },
    "9": {
      id: 9,
      name: "3-10번 (단)",
      number: 9,
      gId: 3,
      gNum: 3,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.179",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "52",
      angle: -39,
      useYn: 1,
      delYn: 0
    },
    "10": {
      id: 10,
      name: "3-11번 4",
      number: 10,
      gId: 5,
      gNum: 5,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.180",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130114400",
      angle: -42,
      useYn: 1,
      delYn: 0
    },
    "11": {
      id: 11,
      name: "3-17번 4",
      number: 11,
      gId: 4,
      gNum: 4,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.80",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130118000",
      angle: -43,
      useYn: 1,
      delYn: 0
    },
    "12": {
      id: 12,
      name: "1_단일로",
      number: 12,
      gId: 4,
      gNum: 4,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.81",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130120400",
      angle: -32,
      useYn: 1,
      delYn: 0
    },
    "13": {
      id: 13,
      name: "2_단일로",
      number: 13,
      gId: 4,
      gNum: 4,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.82",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "53",
      angle: -31,
      useYn: 1,
      delYn: 0
    },
    "14": {
      id: 14,
      name: "3-18번 (단)",
      number: 14,
      gId: 4,
      gNum: 4,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.83",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "10",
      angle: -31,
      useYn: 1,
      delYn: 0
    },
    "15": {
      id: 15,
      name: "151",
      number: 1,
      gId: 7,
      gNum: 1,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.171",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130093900",
      angle: -30,
      useYn: 1,
      delYn: 0
    },
    "16": {
      id: 16,
      name: "152",
      number: 2,
      gId: 7,
      gNum: 1,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.172",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130096200",
      angle: 12,
      useYn: 1,
      delYn: 0
    },
    "17": {
      id: 17,
      name: "2315",
      number: 3,
      gId: 7,
      gNum: 1,
      locType: 0,
      lcType: 3,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "10.1.1.173",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130093000",
      angle: -37,
      useYn: 1,
      delYn: 0
    },
    "18": {
      id: 18,
      name: "3-1번 3",
      number: 99,
      gId: 6,
      gNum: 99,
      locType: 0,
      lcType: 5,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 0,
      comType: 0,
      ip: "172.16.1.2",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "1",
      angle: 0,
      useYn: 1,
      delYn: 0
    },
    "23": {
      id: 23,
      name: "연계#server",
      number: 61,
      gId: 8,
      gNum: 7,
      locType: 0,
      lcType: 4,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 1,
      comType: 1,
      ip: "10.1.1.84",
      port: 7070,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "4130116500",
      angle: 0,
      useYn: 1,
      delYn: 0
    },
    "27": {
      id: 27,
      name: "테스트교차로110",
      number: 62,
      gId: 0,
      gNum: 0,
      locType: 0,
      lcType: 0,
      lamp: 0,
      delta: 3,
      trsCyc: 3,
      aCorrect: 0,
      aOnYn: 1,
      comType: 0,
      ip: "10.10.1.100",
      port: 0,
      offLock: 0,
      maxTrsCyc: 255,
      offsetTuneYn: 1,
      phaseOprMode: 0,
      nodeId: "",
      angle: 0,
      useYn: 1,
      delYn: 0
    }
  };
  export const Column = [
    {
      id: "number",
      text: "번호",
      type: "value",
      width: "5%"
    },
    {
      id: "name",
      text: "명칭",
      type: "text",
      width: "10%"
    },
    {
      id: "aOnYn",
      text: "자동 온라인",
      type: "text",
      width: "5%"
    },
    {
      id: "offLock",
      text: "오프라인 고정",
      type: "text",
      width: "5%"
    },
    {
      id: "gId",
      text: "그룹 ID",
      type: "text",
      width: "5%"
    },
    {
      id: "locType",
      text: "교차로 유형",
      type: "text",
      width: "5%"
    },
    {
      id: "lcType",
      text: "제어기 유형",
      type: "text",
      width: "5%"
    },
    {
      id: "lamp",
      text: "등화기 유형",
      type: "text",
      width: "5%"
    },
    {
      id: "aCorrect",
      text: "자동 오류보정",
      type: "text",
      width: "5%"
    },
    {
      id: "delta",
      text: "최대허용 연동차",
      type: "text",
      width: "5%"
    },
    {
      id: "trsCyc",
      text: "전이 주기수",
      type: "text",
      width: "5%"
    },
    {
      id: "maxTrsCyc",
      text: "최대 전이주기",
      type: "text",
      width: "5%"
    },
    {
      id: "offsetTuneYn",
      text: "연동미세 조정여부",
      type: "text",
      width: "5%"
    },
    {
      id: "phaseOprMode",
      text: "현시 운영모드",
      type: "text",
      width: "5%"
    },
    {
      id: "comType",
      text: "통신방식",
      type: "text",
      width: "5%"
    },
    {
      id: "ip",
      text: "IP",
      type: "text",
      width: "10%"
    },
    {
      id: "port",
      text: "포트 번호",
      type: "text",
      width: "5%"
    },
    {
      id: "useYn",
      text: "사용 여부",
      type: "text",
      width: "5%"
    }
  ];
  